org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
net.minecraftforge.gradle.merge-source-sets=true

java_version=21
minecraft_version=1.20.6
minecraft_version_range=[1.20.5,1.20.6]
forge_version=50.2.10
forge_version_range=[50,)
loader_version_range=[50,)
lombok_version=1.18.48

mod_id=smoothscroll
mod_name=Smooth Scroll
mod_license=GPL-3.0
mod_version=1.0.0
mod_group_id=com.ninix.smoothscroll
mod_authors=Ninix44
mod_description=Smooth scrolling for chat, hotbar and menu lists
